### ISSUE TITLE
pistache client crash when server shutdowns

### ISSUE THREAD

**Issue by bichkhe** [oktal/pistache#152]
I created a client using pistache and a server by Golang to receive request.
` for (int i = 0; i < count; ++i)
    {
        std::cout << "send JSON" << URL;
        string json = "{\"id\":\"123\"}";
        auto resp = client.post(URL).body(json).send();
        resp.then([&](Http::Response response)
        {
            ++completedRequests;
            std::cout << "Response code = " << response.code() << std::endl;
            auto body = response.body();
            if (!body.empty())
                  std::cout << "Response body = " << body << std::endl;
            }, Async::IgnoreException);
        responses.push_back(std::move(resp));
    }

    auto sync = Async::whenAll(responses.begin(), responses.end());
    Async::Barrier<std::vector < Http::Response >> barrier(sync);`

When I shutdown server, client crash immediately with call `terminate called after throwing an instance of 'std::bad_function_call'
  what():  bad_function_call

Thread 2 "rest_v1.0" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff6a54700 (LWP 36772)]
0x00007ffff6fb0428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff6fb0428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff6fb202a in __GI_abort () at abort.c:89
#2  0x00007ffff75ea84d in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff75e86b6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff75e8701 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff7613d38 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff6d656ba in start_thread (arg=0x7ffff6a54700) at pthread_create.c:333
#7  0x00007ffff70823dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
`

Please show me to fix it.

**Comment by xoac** [comment]
See #128 There is @oktal (maintainer) comment that client is really buggy. It's look he is really busy, so if you need this usable now, better use golang client.
